#!/bin/sh

echo "setting rebase on pull to always"
git config branch.autosetuprebase always

echo "adding git incoming and git outgoing"
git config --global alias.incoming '!git remote update -p; git log ..@{u}'
git config --global alias.outgoing 'log @{u}..'
